grails-app/controllers/org/weceem/controllers/WcmSynchronizationController.groovy
package org.weceem.controllers

import org.weceem.content.*
import org.weceem.files.*
import grails.converters.JSON

/**
 * WcmSynchronizationController.
 *
 * @author Sergei Shushkevich
 */
class WcmSynchronizationController {

    def wcmContentRepositoryService
    def wcmContentDependencyService

    def index = {}

    def list = {
        def spaces = WcmSpace.list()
        render (view: "list", model: [spaces: spaces])
    }

    /**
     * Renders list of files and WcmContent objects which need to be synchonized.
     */
    def synchronizationList = {
        def space = WcmSpace.get(params.id)
        def result = wcmContentRepositoryService.synchronizeSpace(space)
        def createdContent = result.created
        def missedFiles = result.missed
        def dirnum = createdContent.findAll{c-> c instanceof WcmContentDirectory}.size()
        def filenum = createdContent.size() - dirnum
        def hardRefs = [:]
        missedFiles.each { f ->
            hardRefs[f.ident()] = wcmContentDependencyService.getDependenciesOf(f).any { r -> r.isInstanceOf(WcmVirtualContent)  }
        }
        render (view: "fileList", model: [
            missingFiles: missedFiles, 
            missingFilesHardRefs: hardRefs,
            createdContent: createdContent, 
            space: space, 
            dirnum: dirnum, 
            filenum: filenum])
    }
    
    /**
     * Delete content by set of ids
     *
     */
    def delete = {
        def pattern = ~/delete-\d+/
        def idpattern = ~/\d+/
        // @todo these must happen in leaf --> parent order or we get errors
        // Alternatively we delete parents first and skip descendents.
        def nodes = []
        for (p in params){
            if (pattern.matcher(p.key).matches()){
                def id = idpattern.matcher(p.key)[0]
                nodes << WcmContentFile.get(id)
            }
        }
        if (nodes) {
            wcmContentRepositoryService.removeAllReferencesTo(nodes)
            wcmContentRepositoryService.deleteNodes(nodes, true)
        }
        redirect(controller: "wcmRepository")
     }

    def done = {
        redirect(controller: "wcmRepository")
    }
    
}

grails-app/views/wcmSynchronization/fileList.gsp
<html>
  <head>
    <meta name="layout" content="${wcm.adminLayout().toString()}"/>
    <title><g:message code="synchronization.title"/></title>
  </head>
  <body >
    <nav:set path="plugin.weceem.weceem_menu/administration" scope="plugin.weceem.weceem_menu"/>
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-xs-12">
          <h1>File Synchronization of space ${space.name.encodeAsHTML()} complete.</h1>
        </div>
      </div>

      <g:form controller="wcmSynchronization">
        <g:if test="${createdContent.size() != 0}">
          <div class="row">
            <div class="col-md-12 col-xs-12">
              <div class="message ui-state-highlight ui-corner-all">
                ${dirnum} directories and ${filenum} files were added to the space ${space.name}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 col-xs-12">
                <input type="button" class="btn btn-default"  onclick="$('#moreInfoDiv').toggle()" value="Show added content"/>
            </div>
          </div>
          <div class="row">
            <div id="moreInfoDiv" class="col-md-12 col-xs-12" style="display: none">
                <table class="standard">
                    <thead>
                        <tr>
                            <th width="15px"><g:message code="synchronization.header.contentTitle"/></th>
                            <th width="15px"><g:message code="synchronization.header.relativePath"/></th>
                        </tr>
                    </thead>
                    <tbody>
                         <g:each var="cont" in="${createdContent}">
                            <tr>
                                <td>${cont.title}</td>
                                <td>${cont.toRelativePath()}</td>
                            </tr>
                         </g:each>
                    </tbody>
                </table>
            </div>
          </div>
        </g:if>

        <g:if test="${missingFiles.size()}">
          <div class="row">
            <div class="col-md-12 col-xs-12">
              <div class="message ui-state-highlight ui-corner-all">
                The following nodes were found referencing files that no longer exist in the filesystem. To remove nodes click the checkboxes and then press Delete.
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 col-xs-12">
                <table class="standard">
                    <thead>
                        <tr>
                            <th width="15px"><g:message code="synchronization.header.contentTitle"/></th>
                            <th width="15px"><g:message code="synchronization.header.relativePath"/></th>
                            <th width="15px">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                         <g:each var="cont" in="${missingFiles}">
                            <tr>
                                <td>${cont.title}</td>
                                <td>${cont.toRelativePath()}</td>
                                <td><g:if test="${missingFilesHardRefs[cont.ident()]}">
                                    Cannot be deleted, is referenced
                                    </g:if>
                                    <g:else>
                                        <g:checkBox name="delete-${cont.id}" value="${false}" />
                                    </g:else>
                                    </td>
                            </tr>
                         </g:each>
                    </tbody>
                </table>
            </div>
          </div>
          <div class="row">
                <div class="col-md-12 col-xs-12">
                    <g:actionSubmit class="btn btn-default" value="Delete selected" controller="wcmSynchronization" action="delete"/>
                    <g:actionSubmit class="btn btn-default" value="Don't delete anything" controller="wcmSynchronization" action="done"/>
                </div>
          </div>
        </g:if>
        <g:else>
          <div class="row">
            <div class="col-md-12 col-xs-12">
              Good news! Your repository has no content nodes referencing non-existent server files.<br/>
              <g:link controller="wcmRepository" class="btn btn-default">OK</g:link>
            </div>
          </div>
        </g:else>
      </g:form>
    </div>
  </body>
</html>

grails-app/views/wcmSynchronization/index.gsp
<html>
  <head>
    <meta name="layout" content="${wcm.adminLayout().toString()}"/>
    <title><g:message code="synchronization.title"/></title>
  </head>

  <body>
    <nav:set path="plugin.weceem.weceem_menu/administration" scope="plugin.weceem.weceem_menu"/>
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-xs-12">
          <h1><g:message code="synchronization.title"/></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-xs-6">
          <p>Synchronizing a space with the server filesystem will create new content nodes for any directories and
          files that exist in the filesystem but are not currently in the content repository.
          </p>
          <p> You will be given the option to delete any content nodes that refer to server files or directories that
          no longer exist
          </p>
          <p>Please choose the space you would like to synchronize</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 col-xs-12">
          <input type="button" class="btn btn-primary"
          value="${message(code: 'synchronization.action.start')}"
          onclick="document.location.href = '${createLink(action: 'list')}'"/>
        </div>
      </div>
    </div>
  </body>
</html>

grails-app/views/wcmSynchronization/list.gsp
<html>
  <head>
    <meta name="layout" content="${wcm.adminLayout().toString()}"/>
    <title><g:message code="synchronization.title"/></title>
  </head>
  <body>
    <nav:set path="plugin.weceem.weceem_menu/administration" scope="plugin.weceem.weceem_menu"/>
    <div class="container">
       <div class="row">
         <div class="col-md-12 col-xs-12">
            <h1>File Synchronization</h1>
         </div>
       </div>
       <div class="row">
         <div class="col-md-6 col-xs-6">
            <p>Synchronizing a space with the server filesystem will create new content nodes for any directories
               and files that exist in the filesystem but are not currently in the content repository.
            <br/>
            <br>
            You will be given the option to delete any content nodes
            that refer to server files or directories that no longer exist
            </p>
         </div>
         <div class="col-md-6 col-xs-6">
            To begin, please choose the space you would like to synchronize.<br/>
            <g:each in="${spaces}" status="i" var="space">
                <g:link controller="wcmSynchronization" action="synchronizationList" id="${space.id}" class="large">${space.name.encodeAsHTML()} (/${space.aliasURI.encodeAsHTML()})</g:link><br/>
            </g:each>
        </div>
       </div>
    </div>
  </body>
</html>